    var arr = [{name:'ABC News (AU)', value:'abc-news-au'},
            {name:'Al Jazeera English',  value:'al-jazeera-english'},
            {name:'Ars Technica', value: 'ars-technica'},
            {name:'Associated Press', value:'associated-press'},
            {name:'BBC News' , value:'bbc-news'},
            {name:'BBC Sport', value:'bbc-sport'},
            {name:'Bild', value:'blid'},
            {name:'Bloomberg', value:'bloomberg'},
            {name:'Breitbart News', value:'breitbart-news'},    
            {name:'Business Insider', value:'business-insider'},
            {name:'Business Insider (UK)', value:'business-insider-uk'},
            {name:'Buzzfeed', value:'buzzfeed'},
            {name:'CNBC', value:'cnbc'},
            {name:'CNN', value:'cnn'},
            {name:'Daily Mail', value:'daily-mail'},
            {name:'Der Tagesspiegel', value:'der-tagesspiegel'},
            {name:'Die Zeit', value:'die-zeit'},
            {name:'Engadget', value:'engadget'},
            {name:'Entertainment Weekly', value:'entertainment-weekly'},
            {name:'ESPN', value:'espn'},
            {name:'ESPN Cric Info', value:'espn-cric-info'},
            {name:'Financial Times', value:'financial-times'},
            {name:'Focus', value:'focus'},
            {name:'Football Italia', value:'football-italia'},
            {name:'Fortune', value:'fortune'},
            {name:'FourFourTwo', value:'four-four-two'},
            {name:'Fox Sports', value:'fox-sports'},
            {name:'Google News', value:'google-news'},
            {name:'Gruenderszene', value:'gruenderszene'},
            {name:'Hacker News', value:'hacker-news'},
            {name:'Handelsblatt', value:'handelsblatt'},
            {name:'IGN', value:'ign'},
            {name:'Independent', value:'independent'},
            {name:'Mashable', value:'mashable'},
            {name:'Metro', value:'metro'},
            {name:'Mirror', value:'mirror'},
            {name:'MTV News', value:'mtv-news'},
            {name:'MTV News (UK)', value:'mtv-news-uk'},
            {name:'National Geographic', value:'national-geographic'},
            {name:'New Scientist', value:'new-scientist'},
            {name:'Newsweek', value:'newsweek'},
            {name:'New York Magazine', value:'new-york-magazine'},
            {name:'NFL News', value:'nfl-news'},
            {name:'Polygon', value:'polygon'},
            {name:'Recode', value:'recode'},
            {name:'Reddit /r/all', value:'reddit-r-all'},
            {name:'Reuters', value:'reuters'},
            {name:'Spiegel Online', value:'spiegel-online'},
            {name:'T3n', value:'t3n'},
            {name:'TalkSport', value:'talksport'},
            {name:'TechCrunch', value:'techcrunch'},
            {name:'TechRadar', value:'techradar'},
            {name:'The Economist', value:'the-economist'},
            {name:'The Guardian (AU)', value:'the-guardian-au'},
            {name:'The Guardian (UK)', value:'the-guardian-uk'},
            {name:'The Hindu', value:'the-hindu'},
            {name:'The Huffington Post', value:'the-huffington-post'},
            {name:'The Lad Bible', value:'the-lad-bible'},
            {name:'The New York Times', value:'the-new-york-times'},
            {name:'The Next Web', value:'the-next-web'},
            {name:'The Sport Bible', value:'the-sport-bible'},
            {name:'The Telegraph', value:'the-telegraph'},
            {name:'The Times of India', value:'the-times-of-india'},
            {name:'The Verge', value:'the-verge'},
            {name:'The Wall Street Journal', value:'the-wall-street-journal'},
            {name:'The Washington Post', value:'the-washington-post'},
            {name:'Time', value:'time'},
            {name:'USA Today', value:'usa-today'},
            {name:'Wired.de', value:'wired-de'},
            {name:'Wirtschafts Woche', value:'wirtschafts-woche'}
            
        ]
        export default arr
        